Firebase 전화번호 인증 함수 구현
Team-DDG/Match-Making-Mobile pull request #24
Opened 2020-08-24 12:56 UTC by choi-seung-min

전화번호 인증 페이지 구현 후 사용할 firebase service의 전화번호 인증 함수 구현

2020-08-24 13:32 UTC, kimdohun0104 requested changes

2020-08-24 13:32 UTC, kimdohun0104 commented on lib/data/error/handler/network_error_handler.dart
> +      case HttpStatus.conflict: throw AlreadyExistException();
그냥 http상태와 같은 이름으로 conflicexception이 더 좋을 것 같습니다.

2020-08-24 13:32 UTC, kimdohun0104 commented on lib/ui/input/input_profile_model.dart
> +      _lolResponse = await _lolService.getLolBySummonerName({
Map을 넘기지 않고, summonername만 넘기고 서비스에서 map으로 감싸는 것은 어떻게 생각하세요?

2020-08-24 13:32 UTC, kimdohun0104 commented on lib/ui/input/input_profile_model.dart
> +      await _lolService.postLolBySummonerName({
이것도 위와 같이 서비스에서 map으로 감싸는군 어떻게 생각해요

2020-08-24 13:32 UTC, kimdohun0104 commented on lib/ui/input/lol/input_lol_page.dart
> +                  model.postLolBySummonerName().catchError((e) => {
이런 부분은 함수로 _onClick@@@ 이런씯트로 빼줍시당

2020-08-24 13:32 UTC, kimdohun0104 commented on lib/ui/input/lol/input_lol_page.dart
>            child: GestureDetector(
아래의 gesturedetector랑 중복되는 것 같은데?
그냥 코드리뷰애서 이상하게 뜨는건가

2020-08-24 13:32 UTC, kimdohun0104 commented on lib/data/service/firebase_auth_service.dart
> +      PhoneVerificationCompleted completed,
이건 일종의 콜백 맞죠? 
이런 파이어베이스 플러그인에서 구현된 것을 메소드의 파라미터로 넘긴다는 것은 모델에서 파이어베이스에 대한 종속성이 생기는 것 입내다. 
그래서 그냥 모델에서 일반적인 함수를 넘길수 있도록 변경해야할듯

2020-08-25 10:35 UTC, kimdohun0104 commented on lib/data/service/firebase_auth_service.dart
> +    final PhoneCodeSent phoneCodeSent = codeSent;
바로 completed 같은 함수를 바로 verifyPhoneNumber에 넘겨줄 수 없나요?
꼭 변수를 생성해야 하는건가요?

2020-08-25 10:37 UTC, choi-seung-min commented on lib/data/service/firebase_auth_service.dart
> +    final PhoneCodeSent phoneCodeSent = codeSent;
verifyPhoneNumber에서 위의 자료형들을 파라미터로 받습니다. 따라서 저렇게 처리를 진행했습니다

2020-08-25 10:50 UTC, kimdohun0104 approved these changes

2020-08-25 10:56 UTC, merged